export * from "./About";
export * from "./Contact";
export * from "./Faq";
export * from "./Hero";
export * from "./Porfolio";
export * from "./Skills";
export * from "./Testimonials";
export * from "./Imprint";
export * from "./Process";
